### PR TITLE
Tests: update Ansible and Ubuntu version

### PR DESCRIPTION
**Pull request by pilou-**

### CODE REVIEW

**Comment by FlogFr** [comment]
@pilou- who uses the `ansible-boot-lxc`?

**Comment by pilou-** [comment]
Other significant updates are required, I am working on it.

**Comment by pilou-** [comment]
@aRkadeFR some private projects.

**Comment by FlogFr** [comment]
@pilou- okok

**Comment by jpic** [comment]
Did you consider upgrading to https://github.com/peopledoc/ansible-boot-lxd ?

**Comment by pilou-** [comment]
@jpic nope, I didn't know this one, thanks for the pointer :)

In order to fix the CI, the current plan is to:
1. remove the dependency to the unmaintained project https://github.com/peopledoc/ansible-setup
2. setup of test environment: use Ansible tasks instead of bash

**Pull request closed without merging**
